filter:
  excluded_paths:
    - "docker/"
    - "karmabot/tests/"
build:
    environment:
        php:
            version: 7.1.0
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=karmabot/phpunit.xml'
                coverage:
                    file: 'karmabot/phpunit.xml'
                    format: 'clover'
