version: '2'

services:
    workspace:
        build:
            context: ./docker/workspace
            args:
                - TZ=UTC
        volumes:
            - ".:/var/www"
        extra_hosts:
            - "dockerhost:172.17.0.1"
        tty: true

    bot:
        build:
            context: ./docker/bot
        command: "/bin/bash /start.sh"
        volumes_from:
            - workspace
        links:
            - workspace
        extra_hosts:
            - "dockerhost:172.17.0.1"
        environment:
            - PHP_IDE_CONFIG="serverName=laravel"
        tty: true

    mysql:
        build: 
            context: ./docker/mysql
            args:
                - DB_DATABASE=karma
                - DB_USERNAME=root
                - DB_PASSWORD=root
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3308:3306"

    redis:
        build: ./docker/redis
        volumes:
            - redis:/data
        ports:
            - "6381:6379"

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
