version: '2'

services:
    apps:
        image: tianon/true
        volumes:
            - ".:/var/www"
        tty: true

    workspace:
        build:
            context: ./docker/workspace
            args:
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - TZ=UTC
        volumes_from:
            - apps
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.17.0.1"
        ports:
           - "2223:22"
        tty: true

    php_bot:
        build:
            context: ./docker/php-bot
        command: "/bin/bash /start.sh"
        volumes_from:
            - apps
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:172.17.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"
        tty: true

    mysql:
        build: 
            context: ./docker/mysql
            args:
                - MYSQL_DATABASE=karma
                - MYSQL_USER=root
                - MYSQL_PASSWORD=root
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3308:3306"

    redis:
        build: ./docker/redis
        volumes:
            - redis:/data
        ports:
            - "6381:6379"

volumes:
    mysql:
        driver: "local"
    redis:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"
